routes/web.php
<?php

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'],function(){

	Route::get('/',function () {
		return view('admin.dashboard');
	});

	Route::resource('/guru','Admin\Guru\GuruController');
	Route::resource('/siswa','Admin\Siswa\SiswaController');
});
//API
Route::get('guru-api','Admin\Guru\GuruController@Api')->name('api.guru');
Route::get('siswa-api','Admin\Siswa\SiswaController@Api')->name('api.siswa');

app/Http/Controllers/Admin/Guru/GuruController.php
<?php

namespace App\Http\Controllers\Admin\Guru;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Guru;
use Illuminate\Support\Facades\Storage;
use DataTables;

class GuruController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $model = Guru::all();
        return view('admin.guru.index',compact('model'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.guru.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        // dd($request->all());

        if ($request->hasFile('file')) {
            
            $request->validate([
                'nama' => 'required',
                'jenis_kelamin' => 'required',
                'agama' => 'required',
                'jurusan' => 'required',
                'telepon' => 'required',
                'email' => 'nullable|email',
                'file' => 'mimes:jpeg,bmp,png',
            ]);

            $path = $request->file->store('images');
            $request->merge([
                'foto' => $path,
            ]);
        } else {
            $request->validate([
                'nama' => 'required',
                'jenis_kelamin' => 'required',
                'agama' => 'required',
                'jurusan' => 'required',
                'telepon' => 'required',
                'email' => 'nullable|email',
            ]);
        }
        Guru::insert($request->except(['_token','_method','file']));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $model = Guru::find($id);
        return view('admin.guru.detail',compact('model'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = Guru::find($id);
        return view('admin.guru.form',compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if ($request->hasFile('file')) {
            
            $request->validate([
                'nama' => 'required',
                'jenis_kelamin' => 'required',
                'agama' => 'required',
                'tanggal_lahir' => 'required',
                'jurusan' => 'required',
                'telepon' => 'required',
                'email' => 'nullable|email',
                'file' => 'mimes:jpeg,bmp,png',
            ]);
            $oldFile = Guru::select('foto')->where('id',$id)->first()->foto;
            Storage::delete($oldFile);
            $path = $request->file->store('images');
            $request->merge([
                'foto' => $path,
            ]);
        } else {
            $request->validate([
                'nama' => 'required',
                'jenis_kelamin' => 'required',
                'agama' => 'required',
                'tanggal_lahir' => 'required',
                'jurusan' => 'required',
                'telepon' => 'required',
                'email' => 'nullable|email',
            ]);
        }

        Guru::where('id',$id)->update($request->except(['_token','_method','file']));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $foto = Guru::select('foto')->where('id',$id)->first()->foto;
        Storage::delete($foto);
        Guru::destroy($id);
    }

    public function Api(){
        
        $model = Guru::query();

        return DataTables::of($model)
        ->addColumn('opsi', function($model){
            // dd($model);
            return view('layout._action',[
                'model' => $model,
                'url_edit' => route('guru.edit', $model->id),
                'url_destroy' => route('guru.destroy', $model->id),
                'url_show' => route('guru.show', $model->id),
            ]);
        })
        ->editColumn('nama', function($model){
            return ucwords($model->nama);
        })
        ->rawColumns(['opsi'])
        ->addIndexColumn()
        ->toJson();
    }
}

resources/views/admin/guru/detail.blade.php
<div class="row">
    <div class="col-md-6">
      <div class="card" style="width: 18rem;">
        <img src="{{asset('storage/'.$model->foto)}}" class="card-img-top" >
        <div class="card-body">
          <p class="card-text"> @if (isset($model->tentang))
              {{ $model->tentang }} @else
           {{ $model->nama }} lahir pada tanggal {{ $model->tanggal_lahir }} dan sekarang berada di jurusan {{ $model->jurusan }} @endif</p>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card" style="width: 18rem;">
        <div class="card-header">
          Profil Lengkap
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Nama : {{ $model->nama }}</li>
          <li class="list-group-item">Tanggal Lahir : {{ $model->tanggal_lahir }}</li>
          <li class="list-group-item">Jenis Kelamin : {{ $model->jenis_kelamin }} </li>
          <li class="list-group-item">Agama : {{ $model->agama }} </li>
          <li class="list-group-item">Email : {{ $model->email }} </li>
          <li class="list-group-item">Jurusan : {{ $model->jurusan }} </li>
          <li class="list-group-item">No. Telepon : {{ $model->telepon }} </li>
        </ul>
      </div>
    </div>
  </div>

resources/views/admin/guru/form.blade.php
<form action="{{ (isset($model) ? route('guru.update',$model->id): route('guru.store') ) }}" method="post" enctype="multipart/form-data">
  @csrf
  @if(isset($model))
    @method('PUT')
  @else
    @method('POST')
  @endif
  <div class="form-group">
    <label>Nama</label>
    <input required type="text" name="nama" id="nama" class="form-control" autocomplete="off" @isset($model) value="{{ $model->nama }}" @endisset>
  </div>
  <div class="form-group">
    <label>Jenis Kelamin</label>
    <select name="jenis_kelamin" class="form-control">
      <option value="" selected>Pilih Jenis Kelamin..</option>}
      <option @isset($model) @if($model->jenis_kelamin == 'lelaki') selected  @endif @endisset value="lelaki">Lelaki</option>
      <option @isset($model) @if($model->jenis_kelamin == 'perempuan') selected  @endif @endisset value="perempuan">Perempuan</option>
    </select>
  </div>
  <div class="form-group">
    <label>Nama</label>
    <input required type="date" name="tanggal_lahir" id="tanggal_lahir" class="form-control" autocomplete="off" @isset($model) value="{{ $model->tanggal_lahir }}" @endisset>
  </div>
  <div class="form-group">
    <label>Agama</label>
    <select name="agama" class="form-control">
      <option value="" selected>Pilih Agama..</option>}
      <option @isset($model) @if($model->agama == 'islam') selected  @endif @endisset value="islam">Islam</option>
      <option @isset($model) @if($model->agama == 'kristen') selected  @endif @endisset value="kristen">Kristen</option>
      <option @isset($model) @if($model->agama == 'katholik') selected  @endif @endisset value="katholik">Katholik</option>
      <option @isset($model) @if($model->agama == 'budha') selected  @endif @endisset value="budha">Budha</option>
      <option @isset($model) @if($model->agama == 'hindu') selected  @endif @endisset value="hindu">Hindu</option>
    </select>
  </div>
  <div class="form-group">
    <label>Email</label>
    <input type="email" name="email" id="email" class="form-control" autocomplete="off" @isset($model) value="{{ $model->email }}" @endisset>
  </div>
  <div class="form-group">
    <label>Jurusan</label>
    <select name="jurusan" class="form-control">
      <option value="" selected>Pilih Jurusan..</option>}
      <option @isset($model) @if($model->jurusan == 'RPL') selected  @endif @endisset value="RPL">RPL</option>
      <option @isset($model) @if($model->jurusan == 'TKJ') selected  @endif @endisset value="TKJ">TKJ</option>
      <option @isset($model) @if($model->jurusan == 'SIJA') selected  @endif @endisset value="SIJA">SIJA</option>
      <option @isset($model) @if($model->jurusan == 'Mesin') selected  @endif @endisset value="Mesin">Mesin</option>
      <option @isset($model) @if($model->jurusan == 'TTL') selected  @endif @endisset value="TTL">TTL</option>
    </select>
  </div>
  <div class="form-group">
    <label>Telepon</label>
    <input required type="telepon" name="telepon" id="telepon" class="form-control" autocomplete="off" @isset($model) value="{{ $model->telepon }}" @endisset>
  </div>
  <div class="form-group">
    <label>Tentang</label>
    <textarea name="tentang" id="tentang" class="form-control" >@isset($model) {{ $model->tentang }} @endisset</textarea>
  </div>
  <div class="form-group">
    <label>Foto</label>
    <input type="file" name="file" id="file" class="form-control file">
  </div>
</form>

resources/views/admin/guru/index.blade.php
@extends('layout.app')
@section('title','Daftar Guru')

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="card">
	        <div class="card-body">
	            <a href="{{ route('guru.create') }}" class="btn btn-success modal-show" title="Tambah Guru">
				  <i class="fas fa-plus"></i> Tambah Guru
				</a>
	        </div>
	        <table class="table" id="guru">
	              <thead>
	                <tr>
		              <th>No</th>
	                  <th>Nama</th>
	                  <th>Telepon</th>
	                  <th>Jurusan</th>
	                  <th>Kelamin</th>
	                  <th>Opsi</th>
	                </tr>
	              </thead>
	              <tbody>
	              </tbody>
	        </table>
	    </div>
	</div>
</div>
@include('layout.modal')
@include('layout.modal_large')
@endsection



@push('scripts')
	@include('admin.guru.js')
@endpush

resources/views/admin/guru/js.blade.php
<script>
	var table = $('#guru').DataTable({
		ajax: "{{ route('api.guru') }}",
		serverSide: true,
		processing: true,
		columns: [
			{ data: 'DT_RowIndex', name: 'id'},
			{ data: 'nama', name: 'nama' },
			{ data: 'telepon', name: 'telepon' },
			{ data: 'jurusan', name: 'jurusan' },
			{ data: 'jenis_kelamin', name: 'jenis_kelamin' },
			{ data: 'opsi', name: 'opsi' },
		],
	});

	$('body').on('click','.modal-show',function(e){
		
		e.preventDefault();
		var me = $(this),
			url = me.attr('href'),
			title = me.attr('title');

		$('#modal-title').text(title);
		$('#modal-btn-save').text('Simpan');

		$.ajax({
			url: url,
			dataType: 'html',
			success: function(response){
				$('#modal-body').html(response);
			}
		});
		
		$('#modal').modal('show');
	});

	$('#modal-btn-save').click(function (e) {
		// e.preventDefault();

		var form = $('#modal-body form'),
			url = form.attr('action'),
			method = $('input[name=_method]').val();
			data = new FormData(form[0]);
			data.append('_method', method);
			
		$.ajax({
			url: url,
			method: 'POST',
			data:data,
			processData: false,
			contentType: false,
			success: function (response) {
				// console.log(response);
				swal("Sukses!", "Data Berhasil Disimpan", "success");
				$('#modal').modal('hide');
				table.ajax.reload();
			},
			error: function (xhr) {
				errors = xhr.responseJSON.errors;

				$.each(errors,function (i,error) {
					console.log(i+":"+error);
					toastr.error(error, 'Error!!');
				});
			}
		});

	});

	$('body').on('click','.btn-delete',function(e){
			e.preventDefault();
			var me = $(this),
				url = me.attr('href');

			swal({
			  title: "Apakah Kamu Yakin?",
			  text: "Data akan dihapus!",
			  icon: "warning",
			  buttons: true,
			  dangerMode: true,
			})
			.then((willDelete) => {
			  if (willDelete) {
			  	$.ajax({
					url:  url,
					method: 'POST',
					data: {
						_method: 'DELETE',
						_token: '{{ csrf_token() }}', 
					},
					success: function(response){
						// console.log(response);
						 swal("Data sudah dihapus", {
					      icon: "success",
					    });
						table.ajax.reload();

					},
					error: function(xhr){
						console.log(xhr);
					}
				});

			  } else {
			    swal("Data gagal dihapus");
			  }
			});
		});

	$('body').on('click','.btn-show',function(e){
		e.preventDefault();
		var me = $(this),
				url = me.attr('href'),
				title = me.attr('title');
		
		$('.modal-large-title').text(title);

		$.ajax({
			url: url,
			dataType: 'html',
			success: function(response){
				console.log(response);
				$('#modal-large-body').html(response);
			},
		});
		$('#modal-large').modal('show');
	});

</script>